version: '3.8'
services:
  nginx-gateway:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api-service

  api-service:
    build: ./api-service
    environment:
      # Si pruebas local con postgres en este compose, se usa DB_HOST=postgres-db
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
